swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: http://dev.patronage2017.intive-projects.com/organization/info
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        200:
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /transfers:
    x-swagger-router-controller: transfers
    get:
      description: Get info for money transfer
      operationId: transfer
      responses:
        200:
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/TransferResponse"
        # responses may fall through to errors
        400:
          description: Bad Request    
          schema:
            $ref: "#/definitions/ErrorResponse"          
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  name:
    type: string
  AddressDTO:
    properties:
      postCode:
        type: integer
      city:
        type: string
      street:
        type: string
      country:
        type: string
      houseNumber:
        type: string
      apartmentNumber:
         type: integer
  ContactDTO:
    properties:
      email:
        type: string
      phone:
        type: integer
      fax:
        type: integer
      website:
        type: string
  BankAccountDTO:
    properties:
      number:
        type: integer
      bankName:
        type: string
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  TransferResponse:
    properties:
      address:
        $ref: "#/definitions/AddressDTO"     
      contact:
        $ref: "#/definitions/ContactDTO"  
      bankAccount:
        $ref: "#/definitions/BankAccountDTO"  